#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MINIMUM_10_BIT_VALUE            0
#define MAXIMUM_10_BIT_VALUE            1023
#define MINIMUM_25_KHZ_DUTY_CYCLE_VALUE 0
#define MAXIMUM_25_KHZ_DUTY_CYCLE_VALUE 639
#define MINIMUM_PERCENT_VALUE           0
#define MAXIMUM_PERCENT_VALUE           100

#endif